module.exports = {
  home: [
    {
      type: 'category',
      label: '👋 Introduction',
      items: [{ type: "autogenerated", dirName: "introduction" }],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'doc',
      label: '🚩 Examples',
      id: 'examples', // The internal path
    },
    {
      type: 'category',
      label: '📕 Essentials',
      items: [{ type: "autogenerated", dirName: "essentials" }],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'category',
      label: '📚 Extras',
      items: [{ type: "autogenerated", dirName: "extras" }],
      collapsible: true,
      collapsed: true,
    },
 
    {
      type: 'doc',
      label: '🪢 Integrations',
      id: 'integrations/index', // The internal path
    },
    {
      type: 'doc',
      label: '📍 Roadmap',
      id: 'product-roadmap', // The internal path
    },
    {
      type: 'doc',
      label: '📢 Release Notes',
      id: 'release-notes', // The internal path
    },
  ],
  sdks: [
    {
      type: 'doc',
      label: '✨ SDK Features',
      className: 'toggle-right',
      id: 'sdk/features', // The internal path
    },
    {
      type: 'category',
      label: '👩‍💻 Client-side SDKS',
      items: [{ type: "autogenerated", dirName: "sdk/client-side-sdks" }],
      collapsible: true,
      collapsed: true,
    },
    {
      type: 'category',
      label: '💻 Server-side SDKS',
      items: [{ type: "autogenerated", dirName: "sdk/server-side-sdks" }],
      collapsible: true,
      collapsed: true,
    },
  ],
  bestPractices: [
    {
    type: "category",
    label: "🧠 Best Practices",
    link: {type: 'doc', id: 'best-practices/index'},
    collapsed: false,
    collapsible: false,
    items: [{ type: "autogenerated", dirName: "best-practices" }],
    }
  ],
};
