module.exports = {
  home: [
    {
      type: 'category',
      label: '👋 Introduction',
      items: [{ type: "autogenerated", dirName: "introduction" }],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'category',
      label: ' 🖖 The Essentials',
      items: [{ type: "autogenerated", dirName: "essentials" }],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'category',
      label: '🤝 Integrations',
      items: [{ type: "autogenerated", dirName: "integrations" }],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'doc',
      label: '✍️ Release Notes',
      id: 'release-notes', // The internal path
    },
  ],
  sdks: [
    {
      type: "category",
      label: "SDKs",
      link: {type: 'doc', id: 'sdk/index'},
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "sdk" }],
    }
  ],
  bestPractices: [
    {
    type: "category",
    label: "Best Practices",
    link: {type: 'doc', id: 'best-practices/index'},
    collapsed: false,
    collapsible: false,
    items: [{ type: "autogenerated", dirName: "best-practices" }],
    }
  ],
};
