module.exports = {
  collapsed: false,
  home: [
    {
      type: 'autogenerated',
      dirName: 'home'
    }
  ],
  sdks: [
    {
      type: 'autogenerated',
      dirName: 'sdk'
    }
  ],
  tools: [
    {
      type: 'autogenerated',
      dirName: 'tools-and-integrations'
    }
  ],
  bestPractices: [
    {
      type: 'autogenerated',
      dirName: 'best-practices'
    }
  ],
};
