name: Check Markdown links

on: 
  push:
    branches:
    - main
  schedule:
  # Run everyday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 9 * * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: byrnereese/github-action-mkdocs-link-check@1.0
      with:
        verbose-mode: 'yes'
        folder-path: 'docs/'
        file-extension: '.md, .mdx'
