name: Generate PlantUML Diagrams
on:
  pull_request:
    paths:
      - 'diagrams/**.puml'

permissions:
  contents: write
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout Source
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
      - name: Get changed UML files
        id: getfile
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | grep .puml | xargs)" >> "$GITHUB_OUTPUT"

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@2e381afb2bae7e169b76bfb068e8d8b2089106ee
        with:
          args: -v -tsvg "diagrams/**.puml" -o "../static/diagrams"

      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "Generate SVG files for PlantUML diagrams"
